CREWS_FOLDER_NAME = "crews"
CREWS_FOLDER = "./" + CREWS_FOLDER_NAME + "/"
XLS_FOLDER = "./xls/"    
OUT_FOLDER = CREWS_FOLDER  + "output/"
LOG_FOLDER = "./log/"
logfile = LOG_FOLDER + "output.log"
output_log_sheet = OUT_FOLDER + "output_log.xlsx"
